config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  resources :users, :except => [:destroy, :edit, :update, :new] do
    resources :photos, :only => [:show, :create, :destroy]
  end

  get '/register', to: 'users#new'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :photo, styles: { medium: '300', thumb: '100x100#'}
  validates_attachment :photo, presence: true, content_type: {content_type: /\Aimage/}
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  attr_accessor :password, :avatar
  validates_confirmation_of :password
  before_save :encrypt_password

  validates :email, presence: true
  validates_uniqueness_of :username

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user= User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user # return true or false
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to do that.'
      redirect_to log_in_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :find_photo, except: [:create]
  before_action :find_user

  def show
  end

  def create
   photo = @user.photos.new(photo_params)
   if photo.save
     flash[:notice] = "File has been uploaded successfully"
   else
     flash[:error] = "File not created."
   end
   redirect_to user_path(@user)
  end

  def destroy
    @photo.photo = nil
    @phot.save
    @photo.destroy
    flash[:alert] = 'Photo Deleted'
    redirect_to user_path(@user)
  end

  private

    def find_user
      @user = User.find(params[:user_id])
    end

    def find_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:photo, :title)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # doesn't need anything because is not model-backed form
  end

  def create
    user = User.find_by(email:params[:email])
    if user && User.authenticate(params[:email],params[:password])
      flash[:notice] = "You've been logged in"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "User name or password entered incorrectly."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def index
    @photos = Photo.all.shuffle
  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.all
    @photo = Photo.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Welcome to the site!'
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h4> Photosharing Website </h4>

<%= link_to 'Register', register_path %>
<%= link_to 'Login', log_in_path %>
<%= link_to 'Logout', log_out_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= flash[:alert] %>
<%= flash[:notice] %>

</body>
</html>

app/views/photos/index.html.erb
<h4> Show photo page. </h4>

<%= link_to 'Add Photos', new_photo_path %>

app/views/photos/new.html.erb
<h4> Enter a photo of things. </h4>

<h1>File Upload</h1>
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
<%= form.file_field :avatar %>
<% end %>

app/views/photos/show.html.erb
<%= image_tag @photo.photo.url %>

<%= @photo.title %>
<%= link_to 'Delete', user_photo_path(@user, @photo), data: {confirm: 'Are you sure?', method: 'delete'} %>

app/views/users/_form.html.erb
<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit 'Sign Up' %>
<% end %>

app/views/users/index.html.erb
<h4>Users</h4>

  <% @photos.each do |photo| %>
    <figure>
      <%= link_to image_tag(photo.photo.url), user_photo_path(photo.user, photo) %>
      <figcaption><%= photo.name %></figcaption>
    </figure>
  </div>
    <% end %>

app/views/users/new.html.erb
<h4>Sign Up</h4>

<%= render 'form' %>

app/views/users/show.html.erb
<div class='row'>
  <% @photos.each do |photo| %>
    <div class='photo-box'>
      <figure>
        <%= link_to image_tag(photo.photo.url), user_photo_path(@user, photo) %>
        <figcaption><%= photo.name %></figcaption>
      </figure>
    </div>
  <% end %>
</div>

<% if current_user == @user %>

<div class='add-photo'>
  <h4>Add photo</h4>
  <%= form_for([@user, @photo]) do |f| %>
    <div class='form-group'>
      <%= f.label :photo %>
      <%= f.file_field :photo %>
    </div>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit 'Upload Photo' %>
    <% end %>
  <% end %>
</div>